<a href="https://colab.research.google.com/github/drshahizan/Python-big-data/blob/main/Assignment%202a/QUAD/Polars_Assignment2a_GP8_QUAD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Polars

<br>
 <p align="center">
  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKH6i3lJ9tW7bna90G-1SO7QB__e3ri_8MCw&usqp=CAU"/>
 </p>
</br>

🚀 Group Members QUAD (Team 8)

> 1. CHONG KAI ZHE
> 2. TERENCE A/L LOORTHANATHAN
> 3. RISHMA FATHIMA BINTI BASHER
> 4. NUR SYAMALIA FAIQAH BINTI MOHD KAMAL

- **Polars** is both lazy and semi-lazy. It allows you to accomplish most of your work eagerly, similar to Pandas, but it also provides a sophisticated expression syntax that will be optimised and processed within the query engine.

Polars' purpose is to deliver a lightning-fast DataFrame library that makes use of all available cores on your machine. Unlike dask, which attempts to parallelize existing single-threaded libraries such as NumPy and Pandas, Polars is intended from the ground up for parallelization of queries on DataFrames.

Polars goes to great lengths to:

1.   Reduce redundant copies
2.   Traverse memory cache efficiently
3.   Minimize contention in parallelism


For more information about Polars, you can view from [Polars](https://pola-rs.github.io/polars-book/user-guide/index.html).

# Dataset **nyc-yellow-taxi-trip-data** 
Sources: [Kaggle](https://www.kaggle.com/datasets/elemento/nyc-yellow-taxi-trip-data)

Data Collection:
In this dataset, we have collected the data for 4 months particularly:
- Jan 2015: 1.99 GB
- Jan 2016: 1.71 GB
- Feb 2016: 1.78 GB
- Mar 2016: 1.91 GB

In this notebook, we use 'yellow_tripdata_2015-01.csv'. This dataset contain 12748986 records and 19 columns. The variables are:

| Field Name	| Description |
|-------------|-------------|
|VendorID |	A code indicating the TPEP provider that provided the record (Creative Mobile Technologies & VeriFone Inc. )|
|tpep_pickup_datetime	| The date and time when the meter was engaged. |
|tpep_dropoff_datetime	| The date and time when the meter was disengaged. |
| Passenger_count |	The number of passengers in the vehicle. This is a driver-entered value. |
| Trip_distance |	The elapsed trip distance in miles reported by the taximeter.|
| Pickup_longitude	| Longitude where the meter was engaged. |
| Pickup_latitude	| Latitude where the meter was engaged. |
| RateCodeID |	The final rate code in effect at the end of the trip. |
|Store_and_fwd_flag |	This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka “store and forward,” because the vehicle did not have a connection to the server. (Y= store and forward trip N= not a store and forward trip ) |
| Dropoff_longitude	| Longitude where the meter was disengaged. |
| Dropoff_ latitude |	Latitude where the meter was disengaged. |
| Payment_type |	A numeric code signifying how the passenger paid for the trip. |
| Fare_amount |	The time-and-distance fare calculated by the meter. |
| Extra |	Miscellaneous extras and surcharges. Currently, this only includes. the $0.50 and $1 rush hour and overnight charges. |
| MTA_tax	| 0.50 MTA tax that is automatically triggered based on the metered rate in use. |
| Improvement_surcharge	| 0.30 improvement surcharge assessed trips at the flag drop. the improvement surcharge began being levied in 2015. |
| Tip_amount |	Tip amount – This field is automatically populated for credit card tips.Cash tips are not included. |
| Tolls_amount |	Total amount of all tolls paid in trip. |
| Total_amount |	The total amount charged to passengers. Does not include cash tips. |

#Install dataset from kaggle

- Download **nyc-yellow-taxi-trip-data** dataset here: [Kaggle](https://www.kaggle.com/datasets/elemento/nyc-yellow-taxi-trip-data).

To Mount Google Drive in which the dataset can be downloaded into, the code below has to be runned.

In [1]:
# Pull dataset from google drive
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
link = 'https://drive.google.com/file/d/1G0lX1F2ug-DdRw6hbwnSwgmef9z12lMg/view?usp=sharing'
# to get the id part of the file
id = link.split("/")[-2]
 
downloaded = drive.CreateFile({'id':id})
downloaded.GetContentFile('yellow_tripdata_2015-01.csv')

#Installing Polars

Polars is a Python library for data visualization and analysis, and it is not included in the standard Python distribution. Therefore, in order to use it in your Google Colab notebook or any other project, you need to install it first.

In [ ]:
!pip install 'polars[all]'

#or 
#pip install 'polars[numpy,pandas,pyarrow]' to  install a subset of all optional dependencies

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: polars[all] in /usr/local/lib/python3.8/dist-packages (0.15.14)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from polars[all]) (4.4.0)
Requirement already satisfied: connectorx in /usr/local/lib/python3.8/dist-packages (from polars[all]) (0.3.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/dist-packages (from polars[all]) (3.2.2)
Requirement already satisfied: xlsx2csv>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from polars[all]) (0.8.1)
Requirement already satisfied: fsspec in /usr/local/lib/python3.8/dist-packages (from polars[all]) (2022.11.0)
Requirement already satisfied: backports.zoneinfo in /usr/local/lib/python3.8/dist-packages (from polars[all]) (0.2.1)
Requirement already satisfied: pyarrow>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from polars[all]) (9.0.0)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from polars[all]) (1.21.6)
Requirement already satisfied: deltalake in /usr/local/lib/python3.8/dist-packages (from polars[all]) (0.6.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from polars[all]) (1.3.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->polars[all]) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->polars[all]) (1.4.4)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib->polars[all]) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib->polars[all]) (0.11.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->polars[all]) (2022.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.1->matplotlib->polars[all]) (1.15.0)

#Import Polars

Below is the way to import polars as pl.

In [ ]:
import polars as pl

#Read csv file and load the dataset

In [ ]:
df = pl.read_csv('yellow_tripdata_2015-01.csv')

In [ ]:
#load all dataset 

df

shape: (12748986, 19)
┌──────────┬────────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ passenger_ ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ ---      ┆ p_datetime ┆ ff_datetim ┆ count      ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ i64      ┆ ---        ┆ e          ┆ ---        ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│          ┆ str        ┆ ---        ┆ i64        ┆     ┆ f64      ┆ f64        ┆ ---        ┆ f64        │
│          ┆            ┆ str        ┆            ┆     ┆          ┆            ┆ f64        ┆            │
╞══════════╪════════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 2        ┆ 2015-01-15 ┆ 2015-01-15 ┆ 1          ┆ ... ┆ 3.25     ┆ 0.0        ┆ 0.3        ┆ 17.05      │
│          ┆ 19:05:39   ┆ 19:23:42   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 17.8       │
│          ┆ 20:33:38   ┆ 20:53:28   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 10.8       │
│          ┆ 20:33:38   ┆ 20:43:41   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 4.8        │
│          ┆ 20:33:39   ┆ 20:35:31   ┆            ┆     ┆          ┆            ┆            ┆            │
│ ...      ┆ ...        ┆ ...        ┆ ...        ┆ ... ┆ ...      ┆ ...        ┆ ...        ┆ ...        │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 2          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 8.8        │
│          ┆ 19:01:44   ┆ 19:07:26   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 14.3       │
│          ┆ 19:01:44   ┆ 19:15:01   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.25     ┆ 0.0        ┆ 0.3        ┆ 13.55      │
│          ┆ 19:01:44   ┆ 19:17:03   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 6.3        │
│          ┆ 19:01:45   ┆ 19:07:33   ┆            ┆     ┆          ┆            ┆            ┆            │
└──────────┴────────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘

As we can see, Polars pretty-prints the output object, including the column name and datatype as headers.

In [ ]:
# The head function shows by default the first 5 rows of a DataFrame. You can specify the number of rows you want to see (e.g. df.head(10)).

df.head()

shape: (5, 19)
┌──────────┬────────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ passenger_ ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ ---      ┆ p_datetime ┆ ff_datetim ┆ count      ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ i64      ┆ ---        ┆ e          ┆ ---        ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│          ┆ str        ┆ ---        ┆ i64        ┆     ┆ f64      ┆ f64        ┆ ---        ┆ f64        │
│          ┆            ┆ str        ┆            ┆     ┆          ┆            ┆ f64        ┆            │
╞══════════╪════════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 2        ┆ 2015-01-15 ┆ 2015-01-15 ┆ 1          ┆ ... ┆ 3.25     ┆ 0.0        ┆ 0.3        ┆ 17.05      │
│          ┆ 19:05:39   ┆ 19:23:42   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 17.8       │
│          ┆ 20:33:38   ┆ 20:53:28   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 10.8       │
│          ┆ 20:33:38   ┆ 20:43:41   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 4.8        │
│          ┆ 20:33:39   ┆ 20:35:31   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 16.3       │
│          ┆ 20:33:39   ┆ 20:52:58   ┆            ┆     ┆          ┆            ┆            ┆            │
└──────────┴────────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘

#Data Preparation and Cleaning

 If you want to explicitly display the data type of each column, use the dtypes properties:

In [ ]:
df.dtypes

[Int64,
 Utf8,
 Utf8,
 Int64,
 Float64,
 Float64,
 Float64,
 Int64,
 Utf8,
 Float64,
 Float64,
 Int64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64]

describe() returns summary statistics of your DataFrame. It will provide several quick statistics if possible.

In [ ]:
df.describe()

shape: (7, 20)
┌────────┬───────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ descri ┆ Vendo ┆ tpep_picku ┆ tpep_dropo ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ be     ┆ rID   ┆ p_datetime ┆ ff_datetim ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ ---    ┆ ---   ┆ ---        ┆ e          ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│ str    ┆ f64   ┆ str        ┆ ---        ┆     ┆ f64      ┆ f64        ┆ ---        ┆ f64        │
│        ┆       ┆            ┆ str        ┆     ┆          ┆            ┆ f64        ┆            │
╞════════╪═══════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ count  ┆ 1.274 ┆ 12748986   ┆ 12748986   ┆ ... ┆ 1.274898 ┆ 1.2748986e ┆ 1.2748986e ┆ 1.2748986e │
│        ┆ 8986e ┆            ┆            ┆     ┆ 6e7      ┆ 7          ┆ 7          ┆ 7          │
│        ┆ 7     ┆            ┆            ┆     ┆          ┆            ┆            ┆            │
│ null_c ┆ 0.0   ┆ 0          ┆ 0          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 3.0        ┆ 0.0        │
│ ount   ┆       ┆            ┆            ┆     ┆          ┆            ┆            ┆            │
│ mean   ┆ 1.521 ┆ null       ┆ null       ┆ ... ┆ 1.853814 ┆ 0.243498   ┆ 0.283143   ┆ 15.108295  │
│        ┆ 437   ┆            ┆            ┆     ┆          ┆            ┆            ┆            │
│ std    ┆ 0.499 ┆ null       ┆ null       ┆ ... ┆ 1106.432 ┆ 1.527171   ┆ 0.069086   ┆ 1106.50324 │
│        ┆ 54    ┆            ┆            ┆     ┆ 314      ┆            ┆            ┆ 7          │
│ min    ┆ 1.0   ┆ 2015-01-01 ┆ 2015-01-01 ┆ ... ┆ -92.42   ┆ -26.0      ┆ 0.0        ┆ -450.3     │
│        ┆       ┆ 00:00:00   ┆ 00:00:00   ┆     ┆          ┆            ┆            ┆            │
│ max    ┆ 2.0   ┆ 2015-01-31 ┆ 2016-02-02 ┆ ... ┆ 3950588. ┆ 1450.09    ┆ 0.3        ┆ 3950611.6  │
│        ┆       ┆ 23:59:59   ┆ 16:30:52   ┆     ┆ 8        ┆            ┆            ┆            │
│ median ┆ 2.0   ┆ null       ┆ null       ┆ ... ┆ 1.0      ┆ 0.0        ┆ 0.3        ┆ 11.16      │
└────────┴───────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘

To get the column names, use the columns property:

In [ ]:
df.columns

['VendorID',
 'tpep_pickup_datetime',
 'tpep_dropoff_datetime',
 'passenger_count',
 'trip_distance',
 'pickup_longitude',
 'pickup_latitude',
 'RateCodeID',
 'store_and_fwd_flag',
 'dropoff_longitude',
 'dropoff_latitude',
 'payment_type',
 'fare_amount',
 'extra',
 'mta_tax',
 'tip_amount',
 'tolls_amount',
 'improvement_surcharge',
 'total_amount']

To get the content of the DataFrame as a list of tuples, use the rows() method:

In [ ]:
df.rows

<bound method DataFrame.rows of shape: (12748986, 19)
┌──────────┬────────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ passenger_ ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ ---      ┆ p_datetime ┆ ff_datetim ┆ count      ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ i64      ┆ ---        ┆ e          ┆ ---        ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│          ┆ str        ┆ ---        ┆ i64        ┆     ┆ f64      ┆ f64        ┆ ---        ┆ f64        │
│          ┆            ┆ str        ┆            ┆     ┆          ┆            ┆ f64        ┆            │
╞══════════╪════════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 2        ┆ 2015-01-15 ┆ 2015-01-15 ┆ 1          ┆ ... ┆ 3.25     ┆ 0.0        ┆ 0.3        ┆ 17.05      │
│          ┆ 19:05:39   ┆ 19:23:42   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 17.8       │
│          ┆ 20:33:38   ┆ 20:53:28   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 10.8       │
│          ┆ 20:33:38   ┆ 20:43:41   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 4.8        │
│          ┆ 20:33:39   ┆ 20:35:31   ┆            ┆     ┆          ┆            ┆            ┆            │
│ ...      ┆ ...        ┆ ...        ┆ ...        ┆ ... ┆ ...      ┆ ...        ┆ ...        ┆ ...        │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 2          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 8.8        │
│          ┆ 19:01:44   ┆ 19:07:26   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 14.3       │
│          ┆ 19:01:44   ┆ 19:15:01   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.25     ┆ 0.0        ┆ 0.3        ┆ 13.55      │
│          ┆ 19:01:44   ┆ 19:17:03   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 6.3        │
│          ┆ 19:01:45   ┆ 19:07:33   ┆            ┆     ┆          ┆            ┆            ┆            │
└──────────┴────────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘>

Handling missing value

- The value for missing data in Pandas is determined by the column's dtype. Missing data is always displayed as a null value in Polars.

In [ ]:
#count missing value

null_count_df = df.null_count()
print(null_count_df)

shape: (1, 19)
┌──────────┬────────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ passenger_ ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ ---      ┆ p_datetime ┆ ff_datetim ┆ count      ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ u32      ┆ ---        ┆ e          ┆ ---        ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│          ┆ u32        ┆ ---        ┆ u32        ┆     ┆ u32      ┆ u32        ┆ ---        ┆ u32        │
│          ┆            ┆ u32        ┆            ┆     ┆          ┆            ┆ u32        ┆            │
╞══════════╪════════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 0        ┆ 0          ┆ 0          ┆ 0          ┆ ... ┆ 0        ┆ 0          ┆ 3          ┆ 0          │
└──────────┴────────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘

In [ ]:
#filling missing data

df = df.with_column(pl.col('improvement_surcharge').fill_null(pl.mean('improvement_surcharge')),)

After filling missing data, we need to check whether there is still missing data that need to be handled.

In [ ]:
#check missing value

null_count_df = df.null_count()
print(null_count_df)

shape: (1, 19)
┌──────────┬────────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ passenger_ ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ ---      ┆ p_datetime ┆ ff_datetim ┆ count      ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ u32      ┆ ---        ┆ e          ┆ ---        ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│          ┆ u32        ┆ ---        ┆ u32        ┆     ┆ u32      ┆ u32        ┆ ---        ┆ u32        │
│          ┆            ┆ u32        ┆            ┆     ┆          ┆            ┆ u32        ┆            │
╞══════════╪════════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 0        ┆ 0          ┆ 0          ┆ 0          ┆ ... ┆ 0        ┆ 0          ┆ 0          ┆ 0          │
└──────────┴────────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘

Checking duplicate/unique

- Checking for duplicates or unique values can provide valuable insights into the quality and structure of your data, allowing you to make informed decisions and improve the accuracy of your analysis.

In [ ]:
df.unique()

shape: (12748603, 19)
┌──────────┬────────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ passenger_ ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ ---      ┆ p_datetime ┆ ff_datetim ┆ count      ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ i64      ┆ ---        ┆ e          ┆ ---        ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│          ┆ str        ┆ ---        ┆ i64        ┆     ┆ f64      ┆ f64        ┆ ---        ┆ f64        │
│          ┆            ┆ str        ┆            ┆     ┆          ┆            ┆ f64        ┆            │
╞══════════╪════════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 2        ┆ 2015-01-15 ┆ 2015-01-15 ┆ 1          ┆ ... ┆ 3.25     ┆ 0.0        ┆ 0.3        ┆ 17.05      │
│          ┆ 19:05:39   ┆ 19:23:42   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 17.8       │
│          ┆ 20:33:38   ┆ 20:53:28   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 10.8       │
│          ┆ 20:33:38   ┆ 20:43:41   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 4.8        │
│          ┆ 20:33:39   ┆ 20:35:31   ┆            ┆     ┆          ┆            ┆            ┆            │
│ ...      ┆ ...        ┆ ...        ┆ ...        ┆ ... ┆ ...      ┆ ...        ┆ ...        ┆ ...        │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 2          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 8.8        │
│          ┆ 19:01:44   ┆ 19:07:26   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 14.3       │
│          ┆ 19:01:44   ┆ 19:15:01   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.25     ┆ 0.0        ┆ 0.3        ┆ 13.55      │
│          ┆ 19:01:44   ┆ 19:17:03   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 6.3        │
│          ┆ 19:01:45   ┆ 19:07:33   ┆            ┆     ┆          ┆            ┆            ┆            │
└──────────┴────────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘

#Expression
- Polars' primary strength is expression. The expressions provide a versatile structure that not only solves simple questions but can also be easily extended to sophisticated studies. Below, we will go over the fundamental components that will serve as the foundation for all of your questions.

##Select statement

- To select a column we need to do two things. Define the DataFrame we want the data from. And second, select the data that we need. In the example below you see that we select col('*'). The asteriks stands for all columns.

In [ ]:
df.select(pl.col('*'))

shape: (12748986, 19)
┌──────────┬────────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ passenger_ ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ ---      ┆ p_datetime ┆ ff_datetim ┆ count      ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ i64      ┆ ---        ┆ e          ┆ ---        ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│          ┆ str        ┆ ---        ┆ i64        ┆     ┆ f64      ┆ f64        ┆ ---        ┆ f64        │
│          ┆            ┆ str        ┆            ┆     ┆          ┆            ┆ f64        ┆            │
╞══════════╪════════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 2        ┆ 2015-01-15 ┆ 2015-01-15 ┆ 1          ┆ ... ┆ 3.25     ┆ 0.0        ┆ 0.3        ┆ 17.05      │
│          ┆ 19:05:39   ┆ 19:23:42   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 17.8       │
│          ┆ 20:33:38   ┆ 20:53:28   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 10.8       │
│          ┆ 20:33:38   ┆ 20:43:41   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 4.8        │
│          ┆ 20:33:39   ┆ 20:35:31   ┆            ┆     ┆          ┆            ┆            ┆            │
│ ...      ┆ ...        ┆ ...        ┆ ...        ┆ ... ┆ ...      ┆ ...        ┆ ...        ┆ ...        │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 2          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 8.8        │
│          ┆ 19:01:44   ┆ 19:07:26   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 14.3       │
│          ┆ 19:01:44   ┆ 19:15:01   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.25     ┆ 0.0        ┆ 0.3        ┆ 13.55      │
│          ┆ 19:01:44   ┆ 19:17:03   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 6.3        │
│          ┆ 19:01:45   ┆ 19:07:33   ┆            ┆     ┆          ┆            ┆            ┆            │
└──────────┴────────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘

You can also specify the specific columns that you want to return. There are two ways to do this. 
- The first option is to create a list of column names. 
- The second option is to specify each column within a list in the select statement.

In [ ]:
#first option

df.select(pl.col(['payment_type', 'fare_amount']))

shape: (12748986, 2)
┌──────────────┬─────────────┐
│ payment_type ┆ fare_amount │
│ ---          ┆ ---         │
│ i64          ┆ f64         │
╞══════════════╪═════════════╡
│ 1            ┆ 12.0        │
│ 1            ┆ 14.5        │
│ 2            ┆ 9.5         │
│ 2            ┆ 3.5         │
│ ...          ┆ ...         │
│ 1            ┆ 6.0         │
│ 2            ┆ 13.5        │
│ 1            ┆ 10.5        │
│ 2            ┆ 5.5         │
└──────────────┴─────────────┘

In [ ]:
#second option - limit the records to load

df.select([pl.col('payment_type'),pl.col('fare_amount')]).limit(3)

shape: (3, 2)
┌──────────────┬─────────────┐
│ payment_type ┆ fare_amount │
│ ---          ┆ ---         │
│ i64          ┆ f64         │
╞══════════════╪═════════════╡
│ 1            ┆ 12.0        │
│ 1            ┆ 14.5        │
│ 2            ┆ 9.5         │
└──────────────┴─────────────┘

To select a single row in a DataFrame, pass in the row number using the row() method:

In [ ]:
#the result in tuple

df.row(0)

(2,
 '2015-01-15 19:05:39',
 '2015-01-15 19:23:42',
 1,
 1.59,
 -73.993896484375,
 40.7501106262207,
 1,
 'N',
 -73.97478485107422,
 40.75061798095703,
 1,
 12.0,
 1.0,
 0.5,
 3.25,
 0.0,
 0.3,
 17.05)

##Filter

- The filter option allows us to create a subset of the DataFrame. .

To select multiple rows, Polars recommends using the filter() function. For example, if you want to retrieve all payment_type '1' from the DataFrame, you can use the following expression:

In [ ]:
df.filter(pl.col('payment_type') == 1)

shape: (7881388, 19)
┌──────────┬────────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ passenger_ ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ ---      ┆ p_datetime ┆ ff_datetim ┆ count      ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ i64      ┆ ---        ┆ e          ┆ ---        ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│          ┆ str        ┆ ---        ┆ i64        ┆     ┆ f64      ┆ f64        ┆ ---        ┆ f64        │
│          ┆            ┆ str        ┆            ┆     ┆          ┆            ┆ f64        ┆            │
╞══════════╪════════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 2        ┆ 2015-01-15 ┆ 2015-01-15 ┆ 1          ┆ ... ┆ 3.25     ┆ 0.0        ┆ 0.3        ┆ 17.05      │
│          ┆ 19:05:39   ┆ 19:23:42   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 17.8       │
│          ┆ 20:33:38   ┆ 20:53:28   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 6.7      ┆ 5.33       ┆ 0.3        ┆ 40.33      │
│          ┆ 20:33:39   ┆ 20:53:52   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 3          ┆ ... ┆ 1.66     ┆ 0.0        ┆ 0.3        ┆ 9.96       │
│          ┆ 20:33:39   ┆ 20:42:20   ┆            ┆     ┆          ┆            ┆            ┆            │
│ ...      ┆ ...        ┆ ...        ┆ ...        ┆ ... ┆ ...      ┆ ...        ┆ ...        ┆ ...        │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 1.5      ┆ 0.0        ┆ 0.3        ┆ 15.3       │
│          ┆ 19:01:44   ┆ 19:20:09   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 2          ┆ ... ┆ 1.25     ┆ 0.0        ┆ 0.3        ┆ 7.55       │
│          ┆ 19:01:44   ┆ 19:05:40   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 2          ┆ ... ┆ 2.0      ┆ 0.0        ┆ 0.3        ┆ 8.8        │
│          ┆ 19:01:44   ┆ 19:07:26   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 2.25     ┆ 0.0        ┆ 0.3        ┆ 13.55      │
│          ┆ 19:01:44   ┆ 19:17:03   ┆            ┆     ┆          ┆            ┆            ┆            │
└──────────┴────────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘

##Selecting Rows and Columns

- Very often, you need to select rows and columns at the same time. You can do so by chaining the filter() and select() methods with specific columns, like this:

In [ ]:
df.filter(pl.col('payment_type') == 1).select(['VendorID','payment_type'])

shape: (7881388, 2)
┌──────────┬──────────────┐
│ VendorID ┆ payment_type │
│ ---      ┆ ---          │
│ i64      ┆ i64          │
╞══════════╪══════════════╡
│ 2        ┆ 1            │
│ 1        ┆ 1            │
│ 1        ┆ 1            │
│ 1        ┆ 1            │
│ ...      ┆ ...          │
│ 1        ┆ 1            │
│ 1        ┆ 1            │
│ 1        ┆ 1            │
│ 1        ┆ 1            │
└──────────┴──────────────┘

##Groupby

In [ ]:
# without maintain_order you will get a random order back.
df.groupby('passenger_count', maintain_order=True).count()

shape: (10, 2)
┌─────────────────┬─────────┐
│ passenger_count ┆ count   │
│ ---             ┆ ---     │
│ i64             ┆ u32     │
╞═════════════════╪═════════╡
│ 1               ┆ 8993870 │
│ 3               ┆ 528486  │
│ 2               ┆ 1814594 │
│ 5               ┆ 697645  │
│ ...             ┆ ...     │
│ 0               ┆ 6565    │
│ 9               ┆ 11      │
│ 7               ┆ 9       │
│ 8               ┆ 10      │
└─────────────────┴─────────┘

##With_columns

- with_colums allows you to create new columns for you analyses.

In [ ]:
df.with_columns([pl.col('store_and_fwd_flag').count().alias('count_store_and_fwd_flag')])

shape: (12748986, 20)
┌──────────┬────────────┬────────────┬────────────┬─────┬────────────┬────────────┬────────────┬────────────┐
│ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ passenger_ ┆ ... ┆ tolls_amou ┆ improvemen ┆ total_amou ┆ count_stor │
│ ---      ┆ p_datetime ┆ ff_datetim ┆ count      ┆     ┆ nt         ┆ t_surcharg ┆ nt         ┆ e_and_fwd_ │
│ i64      ┆ ---        ┆ e          ┆ ---        ┆     ┆ ---        ┆ e          ┆ ---        ┆ flag       │
│          ┆ str        ┆ ---        ┆ i64        ┆     ┆ f64        ┆ ---        ┆ f64        ┆ ---        │
│          ┆            ┆ str        ┆            ┆     ┆            ┆ f64        ┆            ┆ u32        │
╞══════════╪════════════╪════════════╪════════════╪═════╪════════════╪════════════╪════════════╪════════════╡
│ 2        ┆ 2015-01-15 ┆ 2015-01-15 ┆ 1          ┆ ... ┆ 0.0        ┆ 0.3        ┆ 17.05      ┆ 12748986   │
│          ┆ 19:05:39   ┆ 19:23:42   ┆            ┆     ┆            ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0        ┆ 0.3        ┆ 17.8       ┆ 12748986   │
│          ┆ 20:33:38   ┆ 20:53:28   ┆            ┆     ┆            ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0        ┆ 0.3        ┆ 10.8       ┆ 12748986   │
│          ┆ 20:33:38   ┆ 20:43:41   ┆            ┆     ┆            ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0        ┆ 0.3        ┆ 4.8        ┆ 12748986   │
│          ┆ 20:33:39   ┆ 20:35:31   ┆            ┆     ┆            ┆            ┆            ┆            │
│ ...      ┆ ...        ┆ ...        ┆ ...        ┆ ... ┆ ...        ┆ ...        ┆ ...        ┆ ...        │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 2          ┆ ... ┆ 0.0        ┆ 0.3        ┆ 8.8        ┆ 12748986   │
│          ┆ 19:01:44   ┆ 19:07:26   ┆            ┆     ┆            ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0        ┆ 0.3        ┆ 14.3       ┆ 12748986   │
│          ┆ 19:01:44   ┆ 19:15:01   ┆            ┆     ┆            ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0        ┆ 0.3        ┆ 13.55      ┆ 12748986   │
│          ┆ 19:01:44   ┆ 19:17:03   ┆            ┆     ┆            ┆            ┆            ┆            │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0        ┆ 0.3        ┆ 6.3        ┆ 12748986   │
│          ┆ 19:01:45   ┆ 19:07:33   ┆            ┆     ┆            ┆            ┆            ┆            │
└──────────┴────────────┴────────────┴────────────┴─────┴────────────┴────────────┴────────────┴────────────┘

# Exploratory Analysis and Insights

In this notebook, we do not visualization. There are several reasons why large data may cause a crash in Google Colab when trying to visualize it:

1. The data may be too large to fit in the memory of the device being used. If this is the case, the device will not be able to handle the data and may crash.

2. The visualization library being used may not be optimized for handling large data sets. This could cause the library to consume too much memory or CPU resources, resulting in a crash.

3. The notebook itself may have insufficient resources to handle the visualization of large data. This could be due to a lack of memory or CPU resources allocated to the notebook.

4. The notebook may be running out of storage space, which could cause the system to crash when trying to save large data.

<br></br>
👇 Below are the examples of exploratory analysis that can be done:

Trip distance with more than 2.0km

In [ ]:
df['trip_distance']>(2.0)

shape: (12748986,)
Series: 'trip_distance' [bool]
[
	false
	true
	false
	false
	true
	true
	true
	false
	true
	false
	false
	false
	...
	false
	false
	false
	false
	true
	false
	true
	true
	false
	false
	true
	false
	false
]

Sum of vendor ID sum

In [ ]:
df.groupby('passenger_count').sum()

shape: (10, 19)
┌────────────┬──────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ passenger_ ┆ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ count      ┆ ---      ┆ p_datetime ┆ ff_datetim ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ ---        ┆ i64      ┆ ---        ┆ e          ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│ i64        ┆          ┆ str        ┆ ---        ┆     ┆ f64      ┆ f64        ┆ ---        ┆ f64        │
│            ┆          ┆            ┆ str        ┆     ┆          ┆            ┆ f64        ┆            │
╞════════════╪══════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 4          ┆ 399713   ┆ null       ┆ null       ┆ ... ┆ 339082.2 ┆ 67775.19   ┆ 68122.2    ┆ 3.7809e6   │
│ 2          ┆ 2767584  ┆ null       ┆ null       ┆ ... ┆ 2.7964e6 ┆ 541015.06  ┆ 503809.799 ┆ 2.7905e7   │
│            ┆          ┆            ┆            ┆     ┆          ┆            ┆ 986        ┆            │
│ 8          ┆ 17       ┆ null       ┆ null       ┆ ... ┆ 12.09    ┆ 9.75       ┆ 2.4        ┆ 324.64     │
│ 6          ┆ 908331   ┆ null       ┆ null       ┆ ... ┆ 684431.7 ┆ 108908.58  ┆ 135804.600 ┆ 6.6506e6   │
│            ┆          ┆            ┆            ┆     ┆ 6        ┆            ┆ 001        ┆            │
│ ...        ┆ ...      ┆ ...        ┆ ...        ┆ ... ┆ ...      ┆ ...        ┆ ...        ┆ ...        │
│ 3          ┆ 849055   ┆ null       ┆ null       ┆ ... ┆ 760939.3 ┆ 136146.5   ┆ 146903.1   ┆ 7.9000e6   │
│ 1          ┆ 13073647 ┆ null       ┆ null       ┆ ... ┆ 1.7968e7 ┆ 2.0696e6   ┆ 2.5449e6   ┆ 1.3591e8   │
│ 5          ┆ 1391726  ┆ null       ┆ null       ┆ ... ┆ 1.0755e6 ┆ 179941.27  ┆ 208379.699 ┆ 1.0377e7   │
│            ┆          ┆            ┆            ┆     ┆          ┆            ┆ 998        ┆            │
│ 7          ┆ 11       ┆ null       ┆ null       ┆ ... ┆ 18.8     ┆ 5.33       ┆ 1.8        ┆ 136.63     │
└────────────┴──────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘

Rounding the distance travelled

In [ ]:
df['trip_distance'].apply(lambda trip_distance : round(trip_distance))

shape: (12748986,)
Series: 'trip_distance' [i64]
[
	2
	3
	2
	0
	3
	9
	2
	1
	18
	1
	1
	1
	...
	2
	2
	2
	2
	4
	2
	2
	2
	1
	1
	3
	1
	1
]

Convert to dict to map store_and_fwd_flag

In [ ]:
mydict = {v:k for k, v in enumerate(df['store_and_fwd_flag'].unique())}

In [ ]:
mydict

{'Y': 0, 'N': 1}

Sorting trip distance in reverse manner

In [ ]:
from polars import col
trip_dist= df.lazy().sort(col("trip_distance"), reverse = True)
trip_dist1=trip_dist.collect()
trip_dist1

shape: (12748986, 19)
┌──────────┬────────────┬────────────┬────────────┬─────┬──────────┬────────────┬────────────┬────────────┐
│ VendorID ┆ tpep_picku ┆ tpep_dropo ┆ passenger_ ┆ ... ┆ tip_amou ┆ tolls_amou ┆ improvemen ┆ total_amou │
│ ---      ┆ p_datetime ┆ ff_datetim ┆ count      ┆     ┆ nt       ┆ nt         ┆ t_surcharg ┆ nt         │
│ i64      ┆ ---        ┆ e          ┆ ---        ┆     ┆ ---      ┆ ---        ┆ e          ┆ ---        │
│          ┆ str        ┆ ---        ┆ i64        ┆     ┆ f64      ┆ f64        ┆ ---        ┆ f64        │
│          ┆            ┆ str        ┆            ┆     ┆          ┆            ┆ f64        ┆            │
╞══════════╪════════════╪════════════╪════════════╪═════╪══════════╪════════════╪════════════╪════════════╡
│ 1        ┆ 2015-01-11 ┆ 2015-01-11 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 35.8       │
│          ┆ 21:55:11   ┆ 22:24:16   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-11 ┆ 2015-01-11 ┆ 2          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 3.3        │
│          ┆ 19:01:17   ┆ 19:14:47   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-02 ┆ 2015-01-02 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.0        ┆ 5.3        │
│          ┆ 15:09:24   ┆ 15:13:08   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-23 ┆ 2015-01-23 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 4.3        │
│          ┆ 15:47:55   ┆ 16:40:57   ┆            ┆     ┆          ┆            ┆            ┆            │
│ ...      ┆ ...        ┆ ...        ┆ ...        ┆ ... ┆ ...      ┆ ...        ┆ ...        ┆ ...        │
│ 1        ┆ 2015-01-10 ┆ 2015-01-10 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 3.3        │
│          ┆ 16:02:49   ┆ 16:02:52   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 2        ┆ 2015-01-29 ┆ 2015-01-29 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 52.8       │
│          ┆ 20:11:11   ┆ 20:11:15   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-26 ┆ 2015-01-26 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 3.3        │
│          ┆ 10:06:21   ┆ 10:06:48   ┆            ┆     ┆          ┆            ┆            ┆            │
│ 1        ┆ 2015-01-26 ┆ 2015-01-26 ┆ 1          ┆ ... ┆ 0.0      ┆ 0.0        ┆ 0.3        ┆ 3.8        │
│          ┆ 10:53:59   ┆ 10:54:03   ┆            ┆     ┆          ┆            ┆            ┆            │
└──────────┴────────────┴────────────┴────────────┴─────┴──────────┴────────────┴────────────┴────────────┘

The trip distance travelled by the Vendor with grouped by the passenger on the car

In [ ]:
pv=df.groupby('passenger_count').pivot(pivot_column='VendorID', values_column='trip_distance').count()
pv

<ipython-input-46-4e4d73e7ff50>:1: DeprecationWarning: `DataFrame.groupby.pivot` is deprecated and will be removed in a future version. Use `DataFrame.pivot` instead.
  pv=df.groupby('passenger_count').pivot(pivot_column='VendorID', values_column='trip_distance').count()

shape: (10, 3)
┌─────────────────┬─────────┬─────────┐
│ passenger_count ┆ 2       ┆ 1       │
│ ---             ┆ ---     ┆ ---     │
│ i64             ┆ u32     ┆ u32     │
╞═════════════════╪═════════╪═════════╡
│ 1               ┆ 4079777 ┆ 4914093 │
│ 3               ┆ 320569  ┆ 207917  │
│ 2               ┆ 952990  ┆ 861604  │
│ 5               ┆ 694081  ┆ 3564    │
│ ...             ┆ ...     ┆ ...     │
│ 0               ┆ 114     ┆ 6451    │
│ 9               ┆ 9       ┆ 2       │
│ 7               ┆ 2       ┆ 7       │
│ 8               ┆ 7       ┆ 3       │
└─────────────────┴─────────┴─────────┘

# Conclusion

To conclude, we can observe that Polars is a very quick EDA project creator to conduct a lot of data processing on huge datasets or big data.